apiVersion: v1
kind: Service
metadata:
  name: arc-demo-service
  namespace: staging
  labels:
    app: arc-demo
    environment: staging
spec:
  selector:
    app: arc-demo
    environment: staging
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082
  type: NodePort
